#!/bin/bash

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    SEP=":"
elif [ "$(uname)" == "Darwin" ]; then
    SEP=":"
elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    SEP=";"
else
    SEP=":"
fi
export CLASSPATH=./.java-libs/saxon/saxon9he.jar$SEP./.java-libs/xerces/xercesSamples.jar$SEP./.java-libs/xerces/xml-apis.jar$SEP./.java-libs/xerces/xercesImpl.jar$SEP$CLASSPATH
